### PR TITLE
feat(pod2): circuit work

### PR DESCRIPTION
**Pull request by ax0**
This PR lays the groundwork for the POD 2 circuits including some minor refactoring.

### CODE REVIEW

**Comment by ludns** [comment]
Is this still a draft? You guys keep pushing to it. If yes, I can switch it to a draft and you can mark it open whenever it's ready to be looked at.

**Comment by ludns** [comment]
Great. I will review. Can you guys rebase, resolve conflicts, and make sure tests pass?

**Comment by ludns** [comment]
Or at least I can an error that the branch cannot be rebased due to conflicts. I think that's because you merged main into this branch, instead of rebasing

**Comment by ax0** [comment]
Voilà.

**Review by ludns — APPROVED** [review]

**Pull request merged**
